### find all
GET http://localhost:8080/songs

### find
GET http://localhost:8080/songs/1

### create
POST http://localhost:8080/songs
Content-Type: application/json

{
  "title": "Title",
  "author": "Author",
  "year": 2028

}

### update
PUT http://localhost:8080/songs/155
Content-Type: application/json

{
  "title": "AKTUALIZACJA",
  "author": "Nowy wykonawca",
  "year": 2091
}

### delete
DELETE http://localhost:8080/songs/1
